# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

max_value = 4000000
fib_term = 0
prev_terms = [0,1]
sum = 0

while true
  fib_term = prev_terms[0] + prev_terms[1]
  break if fib_term > max_value

  sum += fib_term if fib_term.even?

  prev_terms << fib_term
  prev_terms.shift
end

puts "Sum of even-valued terms whose values do not exceed 4M in the Fibonacci sequence: #{sum}"
